### ISSUE TITLE
bug: Could not create window

### ISSUE THREAD

**Issue by m0rkiss** [marc2332/freya#361]
I get this error when i try to run a hello world application.
```
thread 'main' panicked at /home/ignas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/freya-renderer-0.1.6/src/window.rs:85:14:
called `Result::unwrap()` on an `Err` value: Error { raw_code: None, raw_os_message: None, kind: NotFound }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1077:23
   4: freya_renderer::window::WindowEnv<T>::from_config
             at /home/ignas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/freya-renderer-0.1.6/src/window.rs:70:35
   5: freya_renderer::run_app
             at /home/ignas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/freya-renderer-0.1.6/src/lib.rs:57:22
   6: freya::launch::launch_cfg
             at /home/ignas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/freya-0.1.8/src/launch.rs:214:5
   7: freya::launch::launch
             at /home/ignas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/freya-0.1.8/src/launch.rs:33:5
   8: test::main::{{closure}}
             at ./src/main.rs:39:5
```

Tell me if you need other information.

**Comment by marc2332** [comment]
Man, NixOS is really hard to work with isn't it? ahaha Just kidding, but somebody also reported a crash in https://github.com/marc2332/freya/issues/347 and also happened to use NixOS

**Comment by marc2332** [comment]
I'll see what I can do :pray:

**Comment by marc2332** [comment]
I can't really tell why it happens, looks like something from glutin. Sorry for ping @tronical, have you encountered this before?

**Comment by tronical** [comment]
From a quick glance at glutin my guess would be that the Nix environment you're running this in doesn't have `libEGL.so.1.` or `libEGL.so`. Alternatively, if you intend to run this against X11, then you need `libGL.so.1` or `libGL.so`.

**Comment by marc2332** [comment]
Interesting, could you @m0rkiss please see if that is the case? :pray: :crossed_fingers:

**Comment by m0rkiss** [comment]
Yup, that was the problem. It works now!

**Comment by marc2332** [comment]
> Yup, that was the problem. It works now!

Wonderful ✨
