### ISSUE TITLE
issue: Provide better errors for unsupported combination of elements 

### ISSUE THREAD

**Issue by ZeroX-DG** [marc2332/freya#588]
If you have a `rect` that was set to `position: absolute` the app will still run. But as soon as give it some content, it crash the app. A minimal example:

```rs
#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]

use freya::prelude::*;

fn main() {
    launch(app);
}

fn app() -> Element {
    rsx!(
        rect {
            position: "absolute",
            position_top: "10",
            position_left: "10",
            "Just some text"
        }
    )
}
```

That will crash with this error:

```
thread 'main' panicked at crates/core/src/dom/dom_adapter.rs:35:14:
This should exist.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panicking.rs:196:5
   3: core::panicking::panic_str
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panicking.rs:171:5
   4: core::option::expect_failed
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/option.rs:1988:5
   5: core::option::Option<T>::expect
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/option.rs:894:21
   6: <freya_core::dom::dom_adapter::DioxusDOMAdapter as torin::dom_adapter::DOMAdapter<shipyard::entity_id::EntityId>>::get_node
             at ./crates/core/src/dom/dom_adapter.rs:33:26
   7: torin::measure::measure_inner_nodes
             at ./crates/torin/src/measure.rs:378:26
   8: torin::measure::measure_node
             at ./crates/torin/src/measure.rs:193:13
   9: torin::measure::measure_inner_nodes
             at ./crates/torin/src/measure.rs:381:48
  10: torin::measure::measure_node
             at ./crates/torin/src/measure.rs:193:13
  11: torin::measure::measure_inner_nodes
             at ./crates/torin/src/measure.rs:381:48
  12: torin::measure::measure_node
             at ./crates/torin/src/measure.rs:193:13
  13: torin::torin::Torin<Key>::measure
             at ./crates/torin/src/torin.rs:257:52
  14: freya_core::layout::layout_measurer::process_layout
             at ./crates/core/src/layout/layout_measurer.rs:24:9
  15: freya_renderer::app::App<State>::process_layout
             at ./crates/renderer/src/app.rs:305:13
  16: freya_renderer::DesktopRenderer::launch
             at ./crates/renderer/src/lib.rs:77:9
  17: freya::launch::launch_cfg
             at ./crates/freya/src/launch.rs:226:5
  18: freya::launch::launch
             at ./crates/freya/src/launch.rs:36:5
  19: absolute::main
             at ./examples/absolute.rs:9:5
  20: core::ops::function::FnOnce::call_once
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ZeroX-DG** [comment]
Oh my bad. It only crash if the child is a text & not a rect

**Comment by marc2332** [comment]
It's actually not a bug, to display text you have to use the label or paragraph elements. That said, I should add a friendlier error heh

**Comment by marc2332** [comment]
Or maybe fail silently? What do you think it's better?

**Comment by marc2332** [comment]
I think I will just fail silently, will improve it asap, it's easy

**Comment by ZeroX-DG** [comment]
Nice! Yeah it's definitely better to fail silently. In JS you'd have a warning log in the console that warn you about the invalid nested element.

Another cool option is to catch these errors at compile time but that'd be pretty difficult (I imagine) 😄

**Comment by marc2332** [comment]
> Another cool option is to catch these errors at compile time but that'd be pretty difficult (I imagine) 😄

I would love that, but Dioxus doesn't support it :(
