### ISSUE TITLE
Build Failing in windows

### ISSUE THREAD

**Issue by Advik-B** [marc2332/freya#987]
```
PS C:\Users\Advik.DESKTOP-B4PCHRC\Downloads\freya-template-main> cargo run --release
   Compiling skia-bindings v0.72.0
error: failed to run custom build command for `skia-bindings v0.72.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `C:\Users\Advik.DESKTOP-B4PCHRC\Downloads\freya-template-main\target\release\build\skia-bindings-86438357d122b49a\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=DOCS_RS
  cargo:rerun-if-env-changed=SKIA_DEBUG
  HOST: x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.72.0/44350c3dcc5ddd5cc9ae-x86_64-pc-windows-msvc-gl-svg-textlayout
  cargo:rerun-if-env-changed=SKIA_BINARIES_URL
    FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.72.0/skia-binaries-44350c3dcc5ddd5cc9ae-x86_64-pc-windows-msvc-gl-svg-textlayout.tar.gz
  DOWNLOAD AND INSTALL FAILED: curl error code: Some(56)
  curl stderr: Ok("")
  STARTING A FULL BUILD
  cargo:rerun-if-env-changed=CLANGCC
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CLANGCXX
  cargo:rerun-if-env-changed=CXX
  HOST: x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  HOST: x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=SDKTARGETSYSROOT
  cargo:rerun-if-env-changed=SDKROOT
  HOST: x86_64-pc-windows-msvc
  HOST: x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=VCINSTALLDIR
  cargo:rerun-if-env-changed=LLVM_HOME
  cargo:rerun-if-env-changed=USERPROFILE
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Python 3 found: "python"
  Synchronizing Skia dependencies
  Skipping "bin".
  skia\third_party/externals/brotli    @ 6d03dfbedda1615c4cba1211f8d81735575209c8
  ...ird_party/externals/libjpeg-turbo @ ed683925e4897a84b3bffc5c1414c85b97a129a3
  ...rd_party/externals/d3d12allocator @ 169895d529dfce00390a20e69c2f516066fe7a3b
  skia\third_party/externals/freetype  @ 47574f7ea445c8bb751da0fa716424c9c29a6807
  skia\third_party/externals/expat     @ 441f98d02deafd9b090aea568282b28f66a50e36
  skia\third_party/externals/libpng    @ 144b348e072a78e8130ed0acc452c9f039a67bf2
  skia\third_party/externals/harfbuzz  @ 4cfc6d8e173e800df086d7be078da2e8c5cfca19
  skia\third_party/externals/zlib      @ 646b7f569718921d7d4b5b8e22572ff6c76f2596
  skia\third_party/externals/libwebp   @ 2af26267cdfcb63a88e5c74a85927a12d6ca1d76
  skia\third_party/externals/wuffs     @ e3f919ccfe3ef542cfc983a82146070258fb57f8
  ...y/externals/vulkanmemoryallocator @ a6bfc237255a6bac1513f7c1ebde6d8aed6b5191
  skia\third_party/externals/icu       @ a0718d4f121727e30b8d52c7a189ebf5ab52421f
  ...third_party/externals/spirv-cross @ b8fcf307f1f347089e3c46eb4451d27f32ebc8d3
  Skia args: is_official_build=true is_debug=false skia_enable_svg=true skia_enable_gpu=true skia_enable_skottie=false skia_enable_pdf=true skia_use_gl=true skia_use_egl=false skia_use_x11=false skia_use_system_libpng=false skia_use_libwebp_encode=false skia_use_libwebp_decode=false skia_use_system_zlib=false skia_use_xps=false skia_use_dng_sdk=false cc="clang" cxx="clang++" skia_enable_skshaper=true skia_use_icu=true skia_use_system_icu=false skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_harfbuzz=false skia_use_sfntly=false skia_enable_skparagraph=true skia_use_freetype=false skia_use_system_libjpeg_turbo=false skia_use_expat=true skia_use_system_expat=false clang_win="C:\Program Files\LLVM" clang_win_version="C:\Program Files\LLVM\lib\clang\18" target_cpu="x86_64" extra_cflags=["/MD","--target=x86_64-pc-windows-msvc"] extra_asmflags=["--target=x86_64-pc-windows-msvc"]
  Done. Made 80 targets from 49 files in 1225ms
  ninja: Entering directory `C:\Users\Advik.DESKTOP-B4PCHRC\Downloads\freya-template-main\target\release\build\skia-bindings-46827fb51e532ff8\out\skia'
  [0/1] Regenerating ninja files (x99)

  --- stderr
  Checking for "C:\\Program Files\\LLVM\\bin\\clang-cl.exe"
  ninja: error: manifest 'build.ninja' still dirty after 100 tries

  thread 'main' panicked at C:\Users\Advik.DESKTOP-B4PCHRC\.cargo\registry\src\index.crates.io-6f17d22bba15001f\skia-bindings-0.72.0\build_support\skia\config.rs:360:5:
  `ninja` returned an error, please check the output for details.
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:662
     1: core::panicking::panic_fmt
               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\panicking.rs:74
     2: build_script_build::build_support::skia::config::configure_skia::{{closure}}
     3: build_script_build::build_support::skia::config::build
     4: hashbrown::raw::sse2::Group::convert_special_to_empty_and_full_to_deleted
     5: hashbrown::raw::sse2::Group::convert_special_to_empty_and_full_to_deleted
     6: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Advik-B** [comment]
What EXACTLY do I do to fix this issue

**Comment by marc2332** [comment]
hey, did you install Visual Studio 2022 with the `Desktop development with c++` workload?

**Comment by Advik-B** [comment]
Yepp

**Comment by marc2332** [comment]
It seems like a network error, are you using some kind of VPN or very strict firewall?

**Comment by Advik-B** [comment]
> It seems like a network error, are you using some kind of VPN or very strict firewall?

Nope, nothing of that sort

**Comment by marc2332** [comment]
> > It seems like a network error, are you using some kind of VPN or very strict firewall?
> 
> Nope, nothing of that sort

Can you try removing the `target` and build again?

**Comment by Advik-B** [comment]
> > > It seems like a network error, are you using some kind of VPN or very strict firewall?
> > 
> > 
> > Nope, nothing of that sort
> 
> Can you try removing the `target` and build again?

Okay, ill try that

**Comment by marc2332** [comment]
Any luck? I suggest you open an issue in rust-skia if the error persists

**Comment by HaHa421** [comment]
on Windows, the path may be too long, I had the problem solved minimizing the initial root length

**Comment by ravenq** [comment]
i try:
1. download skia from https://github.com/rust-skia/skia-binaries/releases
2. put the gz file to your http server.
3. set SKIA_BINARIES_URL=http://skia url from your http server

it can resolve the network error for download skia bianaries.  but i got a  link error:

```
  = note: skunicode.lib(icu.SkLoadICU.obj) : error LNK2019: unresolved external symbol __std_init_once_link_alternate_names_and_abort referenced in function "bool __cdecl SkLoadICU(void)" (?SkLoadICU@@YA_NXZ)␍
          skunicode.lib(icu.umutex.obj) : error LNK2001: unresolved external symbol __std_init_once_link_alternate_names_and_abort␍
          skia.lib(skia.SkSLRasterPipelineBuilder.obj) : error LNK2019: unresolved external symbol __std_max_element_2 referenced in function "public: void __cdecl SkSL::RP::Program::Dumper::dump(class SkWStream *,bool)" (?dump@Dumper@Program@RP@SkSL@@QEAAXPEAVSkWStream@@_N@Z)␍
          skia.lib(skia.SkSLRasterPipelineBuilder.obj) : error LNK2019: unresolved external symbol __std_max_element_1 referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl SkSL::RP::Program::Dumper::swizzlePtr<unsigned char>(void const *,class SkSpan<unsigned char>)const " (??$swizzlePtr@E@Dumper@Program@RP@SkSL@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBXV?$SkSpan@E@@@Z)␍
          skia.lib(skia.SkSLFindAndDeclareBuiltinFunctions.obj) : error LNK2019: unresolved external symbol __std_find_trivial_8 referenced in function "void __cdecl SkSL::Transform::FindAndDeclareBuiltinFunctions(struct SkSL::Program &)" (?FindAndDeclareBuiltinFunctions@Transform@SkSL@@YAXAEAUProgram@2@@Z)␍     
          skia.lib(skia.SkSLFindAndDeclareBuiltinVariables.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8␍
          skia.lib(skia.SkNWayCanvas.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8␍
          skia.lib(gpu.GrGLCaps.obj) : error LNK2019: unresolved external symbol __std_find_trivial_4 referenced in function "public: bool __cdecl GrGLCaps::programBinaryFormatIsValid(unsigned int)const " (?programBinaryFormatIsValid@GrGLCaps@@QEBA_NI@Z)␍
          D:\code\freya-app\target\debug\deps\freya_app.exe : fatal error LNK1120: 5 unresolved externals␍
```

**Comment by ravenq** [comment]
> > i try:
> > ```
> > 1. download skia from [rust-skia/skia-binaries/releases](https://github.com/rust-skia/skia-binaries/releases)
> > 
> > 2. put the gz file to your http server.
> > 
> > 3. set SKIA_BINARIES_URL=http://skia url from your http server
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it can resolve the network error for download skia bianaries. but i got a link error:
> > ```
> >   = note: skunicode.lib(icu.SkLoadICU.obj) : error LNK2019: unresolved external symbol __std_init_once_link_alternate_names_and_abort referenced in function "bool __cdecl SkLoadICU(void)" (?SkLoadICU@@YA_NXZ)␍
> >           skunicode.lib(icu.umutex.obj) : error LNK2001: unresolved external symbol __std_init_once_link_alternate_names_and_abort␍
> >           skia.lib(skia.SkSLRasterPipelineBuilder.obj) : error LNK2019: unresolved external symbol __std_max_element_2 referenced in function "public: void __cdecl SkSL::RP::Program::Dumper::dump(class SkWStream *,bool)" (?dump@Dumper@Program@RP@SkSL@@QEAAXPEAVSkWStream@@_N@Z)␍
> >           skia.lib(skia.SkSLRasterPipelineBuilder.obj) : error LNK2019: unresolved external symbol __std_max_element_1 referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl SkSL::RP::Program::Dumper::swizzlePtr<unsigned char>(void const *,class SkSpan<unsigned char>)const " (??$swizzlePtr@E@Dumper@Program@RP@SkSL@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBXV?$SkSpan@E@@@Z)␍
> >           skia.lib(skia.SkSLFindAndDeclareBuiltinFunctions.obj) : error LNK2019: unresolved external symbol __std_find_trivial_8 referenced in function "void __cdecl SkSL::Transform::FindAndDeclareBuiltinFunctions(struct SkSL::Program &)" (?FindAndDeclareBuiltinFunctions@Transform@SkSL@@YAXAEAUProgram@2@@Z)␍     
> >           skia.lib(skia.SkSLFindAndDeclareBuiltinVariables.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8␍
> >           skia.lib(skia.SkNWayCanvas.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8␍
> >           skia.lib(gpu.GrGLCaps.obj) : error LNK2019: unresolved external symbol __std_find_trivial_4 referenced in function "public: bool __cdecl GrGLCaps::programBinaryFormatIsValid(unsigned int)const " (?programBinaryFormatIsValid@GrGLCaps@@QEBA_NI@Z)␍
> >           D:\code\freya-app\target\debug\deps\freya_app.exe : fatal error LNK1120: 5 unresolved externals␍
> > ```
> 
> You likely have to update to the latest VS version

thanks! the skia-bindings depends VS2022。

**Comment by marc2332** [comment]
Nice :)
